"""
nuScenes Mini Data Loader for Simple-BEV
=========================================
Loads multi-camera images and generates BEV segmentation ground truth
from the nuScenes mini dataset using nuscenes-devkit.

Camera channels (6 surround-view cameras):
  CAM_FRONT, CAM_FRONT_LEFT, CAM_FRONT_RIGHT,
  CAM_BACK, CAM_BACK_LEFT, CAM_BACK_RIGHT

BEV ground truth is generated by projecting 3D bounding box footprints
onto a top-down grid (200x200) covering a region around the ego vehicle.

Usage:
    from src.data.nuscenes_loader import NuScenesDataset, get_nuscenes_loader
    dataset = NuScenesDataset(dataroot="/data/nuscenes", version="v1.0-mini", cfg=cfg)
    loader  = get_nuscenes_loader(cfg)
"""

import os
from pathlib import Path

import cv2
import numpy as np

CAMERA_CHANNELS = [
    "CAM_FRONT",
    "CAM_FRONT_LEFT",
    "CAM_FRONT_RIGHT",
    "CAM_BACK",
    "CAM_BACK_LEFT",
    "CAM_BACK_RIGHT",
]

# nuScenes category -> BEV class index mapping (matches config.yaml 8-class scheme)
# 0: background, 1: drivable_surface, 2: vehicle, 3: pedestrian,
# 4: cyclist, 5: road_marking, 6: static_obstacle, 7: other
CATEGORY_TO_CLASS = {
    # Vehicles (class 2)
    "vehicle.car": 2,
    "vehicle.truck": 2,
    "vehicle.bus.bendy": 2,
    "vehicle.bus.rigid": 2,
    "vehicle.construction": 2,
    "vehicle.trailer": 2,
    "vehicle.emergency.ambulance": 2,
    "vehicle.emergency.police": 2,
    # Pedestrians (class 3)
    "human.pedestrian.adult": 3,
    "human.pedestrian.child": 3,
    "human.pedestrian.construction_worker": 3,
    "human.pedestrian.police_officer": 3,
    "human.pedestrian.personal_mobility": 3,
    "human.pedestrian.stroller": 3,
    "human.pedestrian.wheelchair": 3,
    # Cyclists (class 4)
    "vehicle.motorcycle": 4,
    "vehicle.bicycle": 4,
    # Static obstacles (class 6)
    "movable_object.barrier": 6,
    "movable_object.trafficcone": 6,
    "movable_object.pushable_pullable": 6,
    "movable_object.debris": 6,
    "static_object.bicycle_rack": 6,
}

# BEV grid parameters: covers [-50m, 50m] x [-50m, 50m] around ego vehicle
BEV_RANGE_M = 50.0  # meters in each direction from ego


class NuScenesDataset:
    """Dataset that loads nuScenes mini samples for Simple-BEV training/inference.

    Each sample provides:
        - imgs:   (6, 3, H, W) float32 normalized camera images
        - labels: (bev_h, bev_w) int64 BEV segmentation ground truth
    """

    def __init__(self, dataroot: str, version: str = "v1.0-mini", cfg: dict = None):
        from nuscenes.nuscenes import NuScenes

        self.cfg = cfg or {}
        self.img_h = self.cfg.get("input", {}).get("height", 224)
        self.img_w = self.cfg.get("input", {}).get("width", 400)
        self.bev_h = self.cfg.get("model", {}).get("bev_h", 200)
        self.bev_w = self.cfg.get("model", {}).get("bev_w", 200)
        self.num_classes = self.cfg.get("model", {}).get("num_classes", 8)

        print(f"  Loading nuScenes {version} from {dataroot} ...")
        self.nusc = NuScenes(version=version, dataroot=dataroot, verbose=False)
        self.samples = self.nusc.sample
        print(f"  Found {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        imgs = self._load_cameras(sample)
        labels = self._generate_bev_labels(sample)
        return imgs, labels

    def _load_cameras(self, sample: dict) -> np.ndarray:
        """Load and preprocess 6 camera images for a sample.

        Returns:
            imgs: (6, 3, H, W) float32 array, normalized to [0, 1]
        """
        imgs = []
        for cam in CAMERA_CHANNELS:
            cam_token = sample["data"][cam]
            cam_data = self.nusc.get("sample_data", cam_token)
            img_path = os.path.join(self.nusc.dataroot, cam_data["filename"])

            img = cv2.imread(img_path)
            if img is None:
                raise FileNotFoundError(f"Cannot read image: {img_path}")
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

            # Resize to model input size
            img = cv2.resize(img, (self.img_w, self.img_h),
                             interpolation=cv2.INTER_LINEAR)

            # Normalize to [0, 1] and convert to CHW
            img = img.astype(np.float32) / 255.0
            img = np.transpose(img, (2, 0, 1))  # (3, H, W)
            imgs.append(img)

        return np.stack(imgs, axis=0)  # (6, 3, H, W)

    def _generate_bev_labels(self, sample: dict) -> np.ndarray:
        """Generate BEV segmentation ground truth from 3D annotations.

        Projects 3D bounding box footprints onto the BEV grid.
        Also marks drivable surface from ego pose context.

        Returns:
            labels: (bev_h, bev_w) int64 array with class indices
        """
        from pyquaternion import Quaternion

        labels = np.zeros((self.bev_h, self.bev_w), dtype=np.int64)

        # Fill drivable surface as a rough circle around ego (class 1)
        # This is an approximation; real drivable surface needs map data
        cy, cx = self.bev_h // 2, self.bev_w // 2
        Y, X = np.ogrid[:self.bev_h, :self.bev_w]
        road_radius = int(min(self.bev_h, self.bev_w) * 0.4)
        road_mask = ((X - cx) ** 2 + (Y - cy) ** 2) <= road_radius ** 2
        labels[road_mask] = 1  # drivable_surface

        # Get ego pose for this sample
        cam_front_token = sample["data"]["CAM_FRONT"]
        cam_front_data = self.nusc.get("sample_data", cam_front_token)
        ego_pose = self.nusc.get("ego_pose", cam_front_data["ego_pose_token"])
        ego_translation = np.array(ego_pose["translation"])

        # Process each annotation (3D bounding box)
        for ann_token in sample["anns"]:
            ann = self.nusc.get("sample_annotation", ann_token)
            category = ann["category_name"]

            cls_id = CATEGORY_TO_CLASS.get(category, 7)  # default to 'other'

            # Get box center and size in global frame
            center = np.array(ann["translation"])
            size = np.array(ann["size"])  # (width, length, height) in meters
            rotation = Quaternion(ann["rotation"])

            # Transform to ego-centric coordinates
            rel_pos = center - ego_translation

            # Get box corners in BEV (top-down view, ignoring Z)
            # size[0] = width, size[1] = length
            half_w = size[0] / 2.0
            half_l = size[1] / 2.0

            # 4 corners of the box footprint (in local box frame)
            corners = np.array([
                [-half_w, -half_l],
                [-half_w,  half_l],
                [ half_w,  half_l],
                [ half_w, -half_l],
            ])

            # Rotate corners by box rotation (yaw only, top-down)
            yaw = rotation.yaw_pitch_roll[0]
            cos_y, sin_y = np.cos(yaw), np.sin(yaw)
            rot_mat = np.array([[cos_y, -sin_y], [sin_y, cos_y]])
            corners_rot = corners @ rot_mat.T

            # Translate to ego-centric position
            corners_ego = corners_rot + rel_pos[:2]

            # Convert from meters to BEV grid coordinates
            # BEV grid: center = ego, range = [-BEV_RANGE_M, BEV_RANGE_M]
            scale_x = self.bev_w / (2.0 * BEV_RANGE_M)
            scale_y = self.bev_h / (2.0 * BEV_RANGE_M)

            corners_bev = np.zeros_like(corners_ego)
            corners_bev[:, 0] = corners_ego[:, 0] * scale_x + self.bev_w / 2.0
            corners_bev[:, 1] = corners_ego[:, 1] * scale_y + self.bev_h / 2.0

            # Check if any corner is within BEV grid
            corners_int = corners_bev.astype(np.int32)
            if (corners_int[:, 0].max() < 0 or corners_int[:, 0].min() >= self.bev_w or
                    corners_int[:, 1].max() < 0 or corners_int[:, 1].min() >= self.bev_h):
                continue

            # Fill polygon on BEV grid
            cv2.fillPoly(labels, [corners_int], cls_id)

        return labels

    def get_all_as_arrays(self, max_samples: int = None):
        """Load all samples into numpy arrays (for compatibility with existing pipeline).

        Returns:
            imgs:   (N, 6, 3, H, W) float32
            labels: (N, bev_h, bev_w) int64
        """
        n = min(len(self), max_samples) if max_samples else len(self)
        all_imgs = []
        all_labels = []

        for i in range(n):
            imgs, labels = self[i]
            all_imgs.append(imgs)
            all_labels.append(labels)
            if (i + 1) % 10 == 0 or i == n - 1:
                print(f"  Loaded {i + 1}/{n} samples")

        return np.stack(all_imgs, axis=0), np.stack(all_labels, axis=0)


def get_nuscenes_loader(cfg: dict, max_samples: int = None):
    """Create a PyTorch DataLoader from nuScenes mini dataset.

    Args:
        cfg: config dict (must have data.nuscenes_dataroot set)
        max_samples: limit number of samples (None = all)

    Returns:
        DataLoader with (imgs, labels) batches
    """
    import torch
    from torch.utils.data import DataLoader, TensorDataset

    data_cfg = cfg.get("data", {})
    dataroot = data_cfg.get("nuscenes_dataroot", "data/nuscenes")
    version = data_cfg.get("nuscenes_version", "v1.0-mini")

    dataset = NuScenesDataset(dataroot=dataroot, version=version, cfg=cfg)
    imgs, labels = dataset.get_all_as_arrays(max_samples=max_samples)

    imgs_t = torch.from_numpy(imgs)
    labels_t = torch.from_numpy(labels)

    batch_size = cfg.get("training", {}).get("batch_size", 2)
    return DataLoader(TensorDataset(imgs_t, labels_t),
                      batch_size=batch_size, shuffle=True)


def get_nuscenes_dataset(cfg: dict, max_samples: int = None):
    """Load nuScenes mini as numpy arrays (for inference pipeline).

    Returns:
        imgs:   (N, 6, 3, H, W) float32
        labels: (N, bev_h, bev_w) int64
    """
    data_cfg = cfg.get("data", {})
    dataroot = data_cfg.get("nuscenes_dataroot", "data/nuscenes")
    version = data_cfg.get("nuscenes_version", "v1.0-mini")

    dataset = NuScenesDataset(dataroot=dataroot, version=version, cfg=cfg)
    return dataset.get_all_as_arrays(max_samples=max_samples)
