"""
nuScenes Mini Data Loader for Simple-BEV
=========================================
Loads multi-camera images and generates BEV segmentation ground truth
from the nuScenes mini dataset using nuscenes-devkit.

Camera channels (6 surround-view cameras):
  CAM_FRONT, CAM_FRONT_LEFT, CAM_FRONT_RIGHT,
  CAM_BACK, CAM_BACK_LEFT, CAM_BACK_RIGHT

Returns camera intrinsics (pix_T_cams) and extrinsics (cam0_T_camXs) alongside
images and BEV labels to match the 3-input Segnet model interface.

BEV ground truth is generated by projecting 3D bounding box footprints
onto a top-down grid (200x200) covering a region around the ego vehicle.

Usage:
    from src.data.nuscenes_loader import NuScenesDataset, get_nuscenes_loader
    dataset = NuScenesDataset(dataroot="/data/nuscenes", version="v1.0-mini", cfg=cfg)
    loader  = get_nuscenes_loader(cfg)
"""

import os
from pathlib import Path

import cv2
import numpy as np

CAMERA_CHANNELS = [
    "CAM_FRONT",
    "CAM_FRONT_LEFT",
    "CAM_FRONT_RIGHT",
    "CAM_BACK",
    "CAM_BACK_LEFT",
    "CAM_BACK_RIGHT",
]

# nuScenes category -> BEV class index mapping (matches config.yaml 8-class scheme)
# 0: background, 1: drivable_surface, 2: vehicle, 3: pedestrian,
# 4: cyclist, 5: road_marking, 6: static_obstacle, 7: other
CATEGORY_TO_CLASS = {
    # Vehicles (class 2)
    "vehicle.car": 2,
    "vehicle.truck": 2,
    "vehicle.bus.bendy": 2,
    "vehicle.bus.rigid": 2,
    "vehicle.construction": 2,
    "vehicle.trailer": 2,
    "vehicle.emergency.ambulance": 2,
    "vehicle.emergency.police": 2,
    # Pedestrians (class 3)
    "human.pedestrian.adult": 3,
    "human.pedestrian.child": 3,
    "human.pedestrian.construction_worker": 3,
    "human.pedestrian.police_officer": 3,
    "human.pedestrian.personal_mobility": 3,
    "human.pedestrian.stroller": 3,
    "human.pedestrian.wheelchair": 3,
    # Cyclists (class 4)
    "vehicle.motorcycle": 4,
    "vehicle.bicycle": 4,
    # Static obstacles (class 6)
    "movable_object.barrier": 6,
    "movable_object.trafficcone": 6,
    "movable_object.pushable_pullable": 6,
    "movable_object.debris": 6,
    "static_object.bicycle_rack": 6,
}

# BEV grid parameters: covers [-50m, 50m] x [-50m, 50m] around ego vehicle
BEV_RANGE_M = 50.0  # metres in each direction from ego


def _build_se3(rotation_quat, translation):
    """
    Build a 4x4 SE(3) matrix from a pyquaternion Quaternion and translation vector.

    Args:
        rotation_quat: pyquaternion.Quaternion
        translation: array-like (3,)

    Returns:
        T: (4, 4) float32 ndarray
    """
    T = np.eye(4, dtype=np.float32)
    T[:3, :3] = rotation_quat.rotation_matrix.astype(np.float32)
    T[:3,  3] = np.array(translation, dtype=np.float32)
    return T


class NuScenesDataset:
    """Dataset that loads nuScenes mini samples for Simple-BEV training/inference.

    Each sample provides:
        - imgs:         (S, 3, H, W) float32 normalised camera images
        - pix_T_cams:   (S, 4, 4)   float32 camera intrinsic matrices (4×4 homogeneous)
        - cam0_T_camXs: (S, 4, 4)   float32 transforms from camX to cam0 (CAM_FRONT)
        - labels:       (bev_h, bev_w) int64 BEV segmentation ground truth
    """

    def __init__(self, dataroot: str, version: str = "v1.0-mini", cfg: dict = None):
        from nuscenes.nuscenes import NuScenes

        self.cfg = cfg or {}
        self.img_h      = self.cfg.get("input", {}).get("height", 224)
        self.img_w      = self.cfg.get("input", {}).get("width",  400)
        self.bev_h      = self.cfg.get("model", {}).get("bev_h", 200)
        self.bev_w      = self.cfg.get("model", {}).get("bev_w", 200)
        self.num_classes = self.cfg.get("model", {}).get("num_classes", 8)

        print(f"  Loading nuScenes {version} from {dataroot} ...")
        self.nusc    = NuScenes(version=version, dataroot=dataroot, verbose=False)
        self.samples = self.nusc.sample
        print(f"  Found {len(self.samples)} samples")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        imgs, pix_T_cams, cam0_T_camXs = self._load_cameras(sample)
        labels = self._generate_bev_labels(sample)
        return imgs, pix_T_cams, cam0_T_camXs, labels

    # ------------------------------------------------------------------
    # Camera loading + calibration
    # ------------------------------------------------------------------

    def _load_cameras(self, sample: dict):
        """Load 6 camera images and their calibration matrices.

        Returns:
            imgs:         (S, 3, H, W) float32 in [0, 1]
            pix_T_cams:   (S, 4, 4)   float32 — intrinsics (4×4 homogeneous)
            cam0_T_camXs: (S, 4, 4)   float32 — camX-to-cam0 extrinsics
        """
        from pyquaternion import Quaternion

        imgs_list       = []
        vehicle_T_cams  = []   # transform from each camera to vehicle frame

        pix_T_cams_list = []

        for cam in CAMERA_CHANNELS:
            cam_token  = sample["data"][cam]
            cam_data   = self.nusc.get("sample_data", cam_token)
            calib      = self.nusc.get("calibrated_sensor",
                                       cam_data["calibrated_sensor_token"])

            # ── Image ──────────────────────────────────────────────────
            img_path = os.path.join(self.nusc.dataroot, cam_data["filename"])
            img = cv2.imread(img_path)
            if img is None:
                raise FileNotFoundError(f"Cannot read image: {img_path}")
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (self.img_w, self.img_h),
                             interpolation=cv2.INTER_LINEAR)
            img = img.astype(np.float32) / 255.0
            img = np.transpose(img, (2, 0, 1))   # (3, H, W)
            imgs_list.append(img)

            # ── Intrinsics: (3×3) → (4×4) homogeneous ─────────────────
            K3 = np.array(calib["camera_intrinsic"], dtype=np.float32)  # (3, 3)
            # Scale K to match the resized image dimensions
            orig_h, orig_w = cam_data["height"], cam_data["width"]
            scale_w = self.img_w / float(orig_w)
            scale_h = self.img_h / float(orig_h)
            K3_scaled = K3.copy()
            K3_scaled[0] *= scale_w   # fx, cx
            K3_scaled[1] *= scale_h   # fy, cy
            K4 = np.eye(4, dtype=np.float32)
            K4[:3, :3] = K3_scaled
            pix_T_cams_list.append(K4)

            # ── Extrinsics: vehicle_T_camX (camera pose in vehicle frame) ──
            T = _build_se3(Quaternion(calib["rotation"]), calib["translation"])
            vehicle_T_cams.append(T)

        # ── Compute cam0_T_camX = inv(vehicle_T_cam0) @ vehicle_T_camX ──
        vehicle_T_cam0 = vehicle_T_cams[0]   # CAM_FRONT in vehicle frame
        # inv of SE(3): [R^T | -R^T*t; 0 | 1]
        R0   = vehicle_T_cam0[:3, :3]
        t0   = vehicle_T_cam0[:3,  3]
        cam0_T_vehicle       = np.eye(4, dtype=np.float32)
        cam0_T_vehicle[:3, :3] = R0.T
        cam0_T_vehicle[:3,  3] = -R0.T @ t0

        cam0_T_camXs_list = []
        for T_veh_camX in vehicle_T_cams:
            cam0_T_camX = cam0_T_vehicle @ T_veh_camX   # (4, 4)
            cam0_T_camXs_list.append(cam0_T_camX)

        imgs         = np.stack(imgs_list,         axis=0)  # (S, 3, H, W)
        pix_T_cams   = np.stack(pix_T_cams_list,   axis=0)  # (S, 4, 4)
        cam0_T_camXs = np.stack(cam0_T_camXs_list, axis=0)  # (S, 4, 4)
        return imgs, pix_T_cams, cam0_T_camXs

    # ------------------------------------------------------------------
    # BEV label generation
    # ------------------------------------------------------------------

    def _generate_bev_labels(self, sample: dict) -> np.ndarray:
        """Generate BEV segmentation ground truth from 3D annotations.

        Projects 3D bounding box footprints onto the BEV grid.
        Also marks drivable surface from ego pose context.

        Returns:
            labels: (bev_h, bev_w) int64 array with class indices
        """
        from pyquaternion import Quaternion

        labels = np.zeros((self.bev_h, self.bev_w), dtype=np.int64)

        # Fill drivable surface as a rough circle around ego (class 1)
        cy, cx = self.bev_h // 2, self.bev_w // 2
        Y, X   = np.ogrid[:self.bev_h, :self.bev_w]
        road_radius = int(min(self.bev_h, self.bev_w) * 0.4)
        road_mask   = ((X - cx) ** 2 + (Y - cy) ** 2) <= road_radius ** 2
        labels[road_mask] = 1  # drivable_surface

        # Get ego pose for this sample
        cam_front_token = sample["data"]["CAM_FRONT"]
        cam_front_data  = self.nusc.get("sample_data", cam_front_token)
        ego_pose        = self.nusc.get("ego_pose", cam_front_data["ego_pose_token"])
        ego_translation = np.array(ego_pose["translation"])

        # Process each annotation (3D bounding box)
        for ann_token in sample["anns"]:
            ann      = self.nusc.get("sample_annotation", ann_token)
            category = ann["category_name"]

            cls_id = CATEGORY_TO_CLASS.get(category, 7)  # default to 'other'

            center   = np.array(ann["translation"])
            size     = np.array(ann["size"])    # (width, length, height)
            rotation = Quaternion(ann["rotation"])

            # Transform to ego-centric coordinates
            rel_pos  = center - ego_translation

            half_w = size[0] / 2.0
            half_l = size[1] / 2.0

            # 4 corners of the box footprint in local box frame
            corners = np.array([
                [-half_w, -half_l],
                [-half_w,  half_l],
                [ half_w,  half_l],
                [ half_w, -half_l],
            ])

            # Rotate corners by box yaw
            yaw     = rotation.yaw_pitch_roll[0]
            cos_y, sin_y = np.cos(yaw), np.sin(yaw)
            rot_mat = np.array([[cos_y, -sin_y], [sin_y, cos_y]])
            corners_rot = corners @ rot_mat.T
            corners_ego = corners_rot + rel_pos[:2]

            # Convert from metres to BEV grid coordinates
            scale_x = self.bev_w / (2.0 * BEV_RANGE_M)
            scale_y = self.bev_h / (2.0 * BEV_RANGE_M)

            corners_bev        = np.zeros_like(corners_ego)
            corners_bev[:, 0]  = corners_ego[:, 0] * scale_x + self.bev_w / 2.0
            corners_bev[:, 1]  = corners_ego[:, 1] * scale_y + self.bev_h / 2.0

            corners_int = corners_bev.astype(np.int32)
            if (corners_int[:, 0].max() < 0 or corners_int[:, 0].min() >= self.bev_w or
                    corners_int[:, 1].max() < 0 or corners_int[:, 1].min() >= self.bev_h):
                continue

            cv2.fillPoly(labels, [corners_int], cls_id)

        return labels

    # ------------------------------------------------------------------
    # Bulk loading helpers
    # ------------------------------------------------------------------

    def get_all_as_arrays(self, max_samples: int = None):
        """Load all samples into numpy arrays.

        Returns:
            imgs:         (N, S, 3, H, W) float32
            pix_T_cams:   (N, S, 4, 4)   float32
            cam0_T_camXs: (N, S, 4, 4)   float32
            labels:       (N, bev_h, bev_w) int64
        """
        n = min(len(self), max_samples) if max_samples else len(self)
        all_imgs, all_pix, all_cam0, all_labels = [], [], [], []

        for i in range(n):
            imgs, pix, cam0, labels = self[i]
            all_imgs.append(imgs)
            all_pix.append(pix)
            all_cam0.append(cam0)
            all_labels.append(labels)
            if (i + 1) % 10 == 0 or i == n - 1:
                print(f"  Loaded {i + 1}/{n} samples")

        return (np.stack(all_imgs,   axis=0),
                np.stack(all_pix,    axis=0),
                np.stack(all_cam0,   axis=0),
                np.stack(all_labels, axis=0))


def get_nuscenes_loader(cfg: dict, max_samples: int = None):
    """Create a PyTorch DataLoader from nuScenes mini dataset.

    Args:
        cfg: config dict (must have data.nuscenes_dataroot set)
        max_samples: limit number of samples (None = all)

    Returns:
        DataLoader yielding (imgs, pix_T_cams, cam0_T_camXs, labels) batches
    """
    import torch
    from torch.utils.data import DataLoader, TensorDataset

    data_cfg  = cfg.get("data", {})
    dataroot  = data_cfg.get("nuscenes_dataroot", "data/nuscenes")
    version   = data_cfg.get("nuscenes_version",  "v1.0-mini")

    dataset = NuScenesDataset(dataroot=dataroot, version=version, cfg=cfg)
    imgs, pix, cam0, labels = dataset.get_all_as_arrays(max_samples=max_samples)

    batch_size = cfg.get("training", {}).get("batch_size", 2)
    return DataLoader(
        TensorDataset(
            torch.from_numpy(imgs),
            torch.from_numpy(pix),
            torch.from_numpy(cam0),
            torch.from_numpy(labels),
        ),
        batch_size=batch_size, shuffle=True)


def get_nuscenes_dataset(cfg: dict, max_samples: int = None):
    """Load nuScenes mini as numpy arrays (for inference pipeline).

    Returns:
        imgs:         (N, S, 3, H, W) float32
        pix_T_cams:   (N, S, 4, 4)   float32
        cam0_T_camXs: (N, S, 4, 4)   float32
        labels:       (N, bev_h, bev_w) int64
    """
    data_cfg = cfg.get("data", {})
    dataroot = data_cfg.get("nuscenes_dataroot", "data/nuscenes")
    version  = data_cfg.get("nuscenes_version",  "v1.0-mini")

    dataset = NuScenesDataset(dataroot=dataroot, version=version, cfg=cfg)
    return dataset.get_all_as_arrays(max_samples=max_samples)
